### ISSUE TITLE
[Feature request] "% complete" for properties

### ISSUE THREAD

**Issue by kckennylau** [rschwiebert/RingApp#18]
Can we have a "% complete" for properties like we have for rings?

**Comment by dyunov** [comment]
Seconding this suggestion, would be very useful for completing the data. Maybe even add the rings to the property page like this:
![image](https://github.com/rschwiebert/RingApp/assets/89836711/0146355a-69cd-42e3-a1e2-755c6eeacb13)

**Comment by dyunov** [comment]
And a similar list with ✔/❌/❔ for the metaproperties too!
