### ISSUE TITLE
connect with pi-base

### ISSUE THREAD

**Issue by StevenClontz** [rschwiebert/RingApp#26]
Hi Ryan, I couldn't find any direct contact info so I hope you don't mind me using the issue tracker to connect.

I (less actively than I wish) help @JamesDabbs maintain https://topology.pi-base.org/ (https://github.com/pi-base/). I came across your app a few weeks ago and was pleased to see that the same pattern of Objects/Properties/Theorems seemed to work well for DaRT.

We're obviously duplicating work, so if you'd like to connect sometime to see how we might be able to work together, please feel free to reach out ot me at sclontz@southalabama.edu to find a time to chat.

**Comment by rschwiebert** [comment]
Talks underway, so closing!
