### ISSUE TITLE
Help setting up environment variables for local development

### ISSUE THREAD

**Issue by enjoysmath** [rschwiebert/RingApp#31]
@rschwiebert 

Where can I find the appropriate env variables to enter into my machine so that I can succesfully run a local dev copy of the site?

Thanks.

EnjoysMath

**Comment by rschwiebert** [comment]
You do not need a functional sendgrid hookup to develop the site locally. The emailing is only used to confirm accounts and to send errors in certain cases.

That said, it would be useful to add a template to have the environment variables at least named, so that they can be adjusted.

**Comment by rschwiebert** [comment]
In commit 550c969557ce3c7ab705a52d7d6eb7921ea09d11 I've added two files to assist with this.

The localenv.sh.example contains a minimal set of environment variables to set, and ringapp/local_settings.py.example has the necessary tweaks for local development laid on top of the regular settings file.

Developers should make local copies of these (without the .example extension) and source the .sh file during setup.  Someone developing on windows will have to adapt it to their system.

The settings file is used like this, in the checkout dir: `python manage.py runserver --settings ringapp.local_settings`
